### ISSUE TITLE
`Factbase::Flatten#it` sorts facts by `_id` as strings, so `to_json`/`to_yaml`/`to_xml` print fact 10 before fact 2

### ISSUE THREAD

**Issue by Favixx** [yegor256/factbase#695]
## What happens

`Factbase::Flatten#it` converts the sorter values to strings before sorting, so
integer `_id` values are ordered lexicographically instead of numerically:

https://github.com/yegor256/factbase/blob/master/lib/factbase/flatten.rb#L22-L28

```ruby
  def it
    @maps
      .sort_by { |m| Array(m[@sorter]).map(&:to_s) }
      .map { |m| m.sort.to_h }
      .map! { |m| m.transform_values { |v| v.size == 1 ? v[0] : v } }
  end
```

`Factbase::ToJSON`, `Factbase::ToYAML` and `Factbase::ToXML` all print through
this class, so as soon as a factbase holds ten or more facts, the printed order
is `1, 10, 11, 12, 2, 3, ...`. Sorting the printed facts by `_id` is the whole
point of this line (#61).

The `.map(&:to_s)` was introduced by 5fd4f461 as the fix for #618
(`sort_by` crashing on incompatible value types). Before that commit the line
was `.sort_by { |m| m[@sorter] || [] }` and the same program below printed
`1, 2, 3, ... 12`. This report is about the ordering, not about the crash
that #618 covered.

## Steps to reproduce

```ruby
require 'factbase'
require 'factbase/to_json'
fb = Factbase.new
(1..12).each { |i| fb.insert._id = i }
puts Factbase::ToJSON.new(fb).json
```

## Observed

```
[{"_id":1},{"_id":10},{"_id":11},{"_id":12},{"_id":2},{"_id":3},{"_id":4},{"_id":5},{"_id":6},{"_id":7},{"_id":8},{"_id":9}]
```

`Factbase::ToXML` and `Factbase::ToYAML` emit the same order, since they use the
same `Flatten`.

Reverting only line 24 to `.sort_by { |m| m[@sorter] || [] }` on the same
commit makes the very same script print:

```
[{"_id":1},{"_id":2},{"_id":3},{"_id":4},{"_id":5},{"_id":6},{"_id":7},{"_id":8},{"_id":9},{"_id":10},{"_id":11},{"_id":12}]
```

## Expected behavior

Facts printed by `ToJSON`, `ToYAML` and `ToXML` should be ordered by the natural
order of the sorter property, so a factbase with integer `_id` values from 1 to
12 prints them as 1, 2, 3, ..., 12, while still not raising when the sorter
values of different facts have incompatible types.

**Comment by 0crat** [comment]
@favixx Thanks for reporting a new bug! You've earned +18 points. By reporting bugs, you help our project improve its quality. If you find anything else in the repository that [doesn't look](https://www.yegor256.com/2018/02/06/where-to-find-more-bugs.html) as good as you might expect, [do not hesitate](https://www.yegor256.com/2014/04/13/bugs-are-welcome.html) to [report](https://www.yegor256.com/2018/04/24/right-way-to-report-bugs.html) it. Your running score is [+54](https://zerocracy.github.io/judges-action/zerocracy-vitals.html); don't forget to check your [Zerocracy account](https://www.zerocracy.com/) too).
